import { BusinessSettings, ServiceItem, ReceiptItem, GovtStatementItem, AuditLog, StaffMember, InspectionChecklist, ComplaintRecord } from '@/types';

export const initialBusinessSettings: BusinessSettings = {
  id: 'biz_01',
  businessName: 'জনি কম্পিউটার',
  lsfcName: 'ঠাকুরগাঁও সদর',
  licenseNo: '০১',
  licenseIssueDate: '2025-02-15',
  licenseExpiryDate: '2027-02-14',
  division: 'রংপুর',
  district: 'ঠাকুরগাঁও',
  upazila: 'ঠাকুরগাঁও সদর',
  addressDetails: 'উপজেলা পরিষদ গেট সংলগ্ন, ঠাকুরগাঁও সদর, ঠাকুরগাঁও',
  inchargeName: 'মোঃ মাহমুদুল হাসান',
  inchargeDesignation: 'কেন্দ্র ইনচার্জ',
  mobile: '০১৭৭৩০১০৬৮৭',
  acLandOffice: 'সহকারী কমিশনার (ভূমি), ঠাকুরগাঁও সদর, ঠাকুরগাঁও',
  ministryMemoRef: 'ভূমি মন্ত্রণালয়ের ২৮/০৭/২০২৫ খ্রি. তারিখের ৩১.০০.০০০.০৫৭.১১.১৪০.২৩-২৪৬ নং স্মারক মোতাবেক।',
  signatureUrl: '/signatures/incharge-sign.png',
  logoUrl: '/logos/lsfc-logo.png',
  optionalMonogramUrl: '',
  tier: 'union_upazila',
  autoReceiptSeq: 679,
};

export const officialServices: ServiceItem[] = [
  {
    id: 'srv_1',
    name: 'ভূ.উ করের আবেদন জমা',
    category: 'ভূমি উন্নয়ন কর',
    feeUnion: 50,
    feeMunicipality: 50,
    feeCityCorp: 50,
    govtFee: 0,
    perPageScanFee: 0,
  },
  {
    id: 'srv_2',
    name: 'ভূ.উ. কর দাখিলা প্রিন্ট',
    category: 'ভূমি উন্নয়ন কর',
    feeUnion: 20,
    feeMunicipality: 20,
    feeCityCorp: 20,
    govtFee: 0,
    perPageScanFee: 0,
  },
  {
    id: 'srv_3',
    name: 'ই নামজারী আবেদন',
    category: 'নামজারি',
    feeUnion: 200,
    feeMunicipality: 250,
    feeCityCorp: 300,
    govtFee: 70, // কোর্ট ফি ২০ + নোটিশ ৫০
    perPageScanFee: 3, // ২০ পাতার অধিক হলে প্রতি পাতা ৩ টাকা
  },
  {
    id: 'srv_4',
    name: 'পর্চা প্রাপ্তির আবেদন',
    category: 'খতিয়ান/পর্চা',
    feeUnion: 100,
    feeMunicipality: 120,
    feeCityCorp: 150,
    govtFee: 100,
    perPageScanFee: 0,
  },
  {
    id: 'srv_5',
    name: 'ডিসি আর প্রদান',
    category: 'নামজারি',
    feeUnion: 100,
    feeMunicipality: 100,
    feeCityCorp: 100,
    govtFee: 1100, // ডি সি আর ফি
    perPageScanFee: 0,
  },
  {
    id: 'srv_6',
    name: 'মিসকেস আবেদন',
    category: 'মিস কেস',
    feeUnion: 100,
    feeMunicipality: 120,
    feeCityCorp: 150,
    govtFee: 50,
    perPageScanFee: 3,
  },
  {
    id: 'srv_7',
    name: 'নকশার মাধ্যমে খাস কৃষি জমির অবস্থান ও বন্দোবস্ত আবেদন',
    category: 'খাস জমি',
    feeUnion: 100,
    feeMunicipality: 120,
    feeCityCorp: 120,
    govtFee: 0,
    perPageScanFee: 3,
  },
  {
    id: 'srv_8',
    name: 'কবুলিয়ত ফরম পূরণ ও এসিল্যান্ড বরাবর দাখিল',
    category: 'বন্দোবস্ত',
    feeUnion: 80,
    feeMunicipality: 80,
    feeCityCorp: 80,
    govtFee: 0,
    perPageScanFee: 0,
  },
  {
    id: 'srv_9',
    name: 'অর্পিত সম্পত্তি লিজ/নবায়ন আবেদন',
    category: 'লিজ',
    feeUnion: 100,
    feeMunicipality: 120,
    feeCityCorp: 150,
    govtFee: 0,
    perPageScanFee: 3,
  },
  {
    id: 'srv_10',
    name: 'মৌজা ম্যাপ বা নকশার আবেদন ও বিতরণ',
    category: 'মৌজা ম্যাপ',
    feeUnion: 100,
    feeMunicipality: 120,
    feeCityCorp: 150,
    govtFee: 520,
    perPageScanFee: 0,
  },
];

export const initialReceipts: ReceiptItem[] = [
  {
    id: 'rcp_101',
    receiptNo: 'LSFC-TS-2026-000675',
    verificationToken: 'vfy_9f82k301x',
    customerId: 'cust_01',
    customerName: 'মোঃ আব্দুল করিম',
    customerMobile: '০১৭১২৩৪৫৬৭৮',
    serviceId: 'srv_3',
    serviceName: 'ই নামজারী আবেদন',
    serviceCategory: 'নামজারি',
    applicationTrackingNo: 'MUT-8912401',
    serviceFee: 200,
    govtFee: 70,
    scannedPages: 18,
    extraScanFee: 0,
    discount: 0,
    totalAmount: 270,
    paymentMethod: 'cash',
    status: 'valid',
    createdAt: '2026-10-01 10:24',
    createdBy: 'মোঃ মাহমুদুল হাসান',
    drivePdfId: 'gdrive_file_rcp_000675',
    drivePdfUrl: 'https://drive.google.com/file/d/sample-rcp-675',
    printCount: 1,
  },
  {
    id: 'rcp_102',
    receiptNo: 'LSFC-TS-2026-000676',
    verificationToken: 'vfy_2e17a490y',
    customerId: 'cust_02',
    customerName: 'মোছাঃ রোকেয়া বেগম',
    customerMobile: '০১৮১৬৯৮৭৬২৪',
    serviceId: 'srv_4',
    serviceName: 'পর্চা প্রাপ্তির আবেদন',
    serviceCategory: 'খতিয়ান/পর্চা',
    applicationTrackingNo: 'KHT-554109',
    serviceFee: 100,
    govtFee: 100,
    scannedPages: 4,
    extraScanFee: 0,
    discount: 0,
    totalAmount: 200,
    paymentMethod: 'bkash',
    status: 'valid',
    createdAt: '2026-10-01 11:15',
    createdBy: 'কম্পিউটার অপারেটর ১',
    drivePdfId: 'gdrive_file_rcp_000676',
    drivePdfUrl: 'https://drive.google.com/file/d/sample-rcp-676',
    printCount: 1,
  },
  {
    id: 'rcp_103',
    receiptNo: 'LSFC-TS-2026-000677',
    verificationToken: 'vfy_89c47012z',
    customerId: 'cust_03',
    customerName: 'মোঃ শফিকুল ইসলাম',
    customerMobile: '০১৯৫১২২৩৩৪৪',
    serviceId: 'srv_1',
    serviceName: 'ভূ.উ করের আবেদন জমা',
    serviceCategory: 'ভূমি উন্নয়ন কর',
    applicationTrackingNo: 'LD-TX-1029',
    serviceFee: 50,
    govtFee: 0,
    scannedPages: 2,
    extraScanFee: 0,
    discount: 0,
    totalAmount: 50,
    paymentMethod: 'cash',
    status: 'valid',
    createdAt: '2026-10-02 09:40',
    createdBy: 'মোঃ মাহমুদুল হাসান',
    drivePdfId: 'gdrive_file_rcp_000677',
    drivePdfUrl: 'https://drive.google.com/file/d/sample-rcp-677',
    printCount: 1,
  },
  {
    id: 'rcp_104',
    receiptNo: 'LSFC-TS-2026-000678',
    verificationToken: 'vfy_41a80931w',
    customerId: 'cust_04',
    customerName: 'তানভীর আহমেদ',
    customerMobile: '০১৭৫০০১১২২৩',
    serviceId: 'srv_5',
    serviceName: 'ডিসি আর প্রদান',
    serviceCategory: 'নামজারি',
    applicationTrackingNo: 'DCR-90412',
    serviceFee: 100,
    govtFee: 1100,
    scannedPages: 6,
    extraScanFee: 0,
    discount: 0,
    totalAmount: 1200,
    paymentMethod: 'cash',
    status: 'valid',
    createdAt: '2026-10-03 10:10',
    createdBy: 'কম্পিউটার অপারেটর ১',
    drivePdfId: 'gdrive_file_rcp_000678',
    drivePdfUrl: 'https://drive.google.com/file/d/sample-rcp-678',
    printCount: 1,
  },
];

export const initialStatements: GovtStatementItem[] = [
  {
    id: 'stmt_01',
    statementNo: 'STMT-2026-09',
    memoNo: 'LSFC/TS/2026/09',
    statementDate: '01/10/2026',
    periodType: 'monthly',
    periodLabel: 'সেপ্টেম্বর/২০২৬',
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    totalApplications: 678,
    breakdown: [
      { serviceName: 'ভূ.উ করের আবেদন জমা', count: 130 },
      { serviceName: 'ভূ.উ. কর দাখিলা প্রিন্ট', count: 200 },
      { serviceName: 'ই নামজারী আবেদন', count: 160 },
      { serviceName: 'পর্চা প্রাপ্তির আবেদন', count: 91 },
      { serviceName: 'ডিসি আর প্রদান', count: 70 },
      { serviceName: 'মিসকেস আবেদন', count: 27 },
    ],
    customRemarks: '',
    status: 'finalized',
    drivePdfId: 'gdrive_file_stmt_sep2026',
    drivePdfUrl: 'https://drive.google.com/file/d/statement-sep-2026',
    createdAt: '2026-10-01',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log_01',
    timestamp: '2026-10-03 10:10:15',
    userId: 'user_owner',
    userName: 'মোঃ মাহমুদুল হাসান',
    userRole: 'owner',
    action: 'CREATE_RECEIPT',
    details: 'রিসিট #LSFC-TS-2026-000678 তৈরি করা হয়েছে (গ্রাহক: তানভীর আহমেদ, সেবা: ডিসি আর প্রদান, ফি: ৳১২০০)',
    ipAddress: '103.145.118.24',
    device: 'Desktop Chrome / Windows 11',
    afterData: { receiptNo: 'LSFC-TS-2026-000678', total: 1200 },
  },
  {
    id: 'log_02',
    timestamp: '2026-10-02 16:30:00',
    userId: 'user_owner',
    userName: 'মোঃ মাহমুদুল হাসান',
    userRole: 'owner',
    action: 'GENERATE_STATEMENT',
    details: 'সেপ্টেম্বর/২০২৬ মাসের সরকারি স্টেটমেন্ট জেনারেট ও গুগল ড্রাইভে সংরক্ষণ করা হয়েছে (মোট আবেদন: ৬৭৮ টি)',
    ipAddress: '103.145.118.24',
    device: 'Desktop Chrome / Windows 11',
  },
  {
    id: 'log_03',
    timestamp: '2026-10-02 09:40:11',
    userId: 'user_staff_1',
    userName: 'কম্পিউটার অপারেটর ১',
    userRole: 'operator',
    action: 'CREATE_RECEIPT',
    details: 'রিসিট #LSFC-TS-2026-000677 তৈরি করা হয়েছে (গ্রাহক: মোঃ শফিকুল ইসলাম, সেবা: ভূ.উ করের আবেদন জমা)',
    ipAddress: '103.145.118.25',
    device: 'Desktop Chrome / Windows 10',
  },
  {
    id: 'log_04',
    timestamp: '2026-10-01 18:00:00',
    userId: 'user_owner',
    userName: 'মোঃ মাহমুদুল হাসান',
    userRole: 'owner',
    action: 'CASH_CLOSING',
    details: '১ অক্টোবর ২০২৬ ডে-এন্ড ক্যাশ ক্লোজিং সম্পন্ন। সম্ভাব্য ক্যাশ: ৳৫২০/-, প্রাপ্ত ক্যাশ: ৳৫২০/- (কোনো গরমিল নেই)',
    ipAddress: '103.145.118.24',
    device: 'Desktop Chrome / Windows 11',
  },
];

export const initialStaff: StaffMember[] = [
  {
    id: 'stf_01',
    name: 'কম্পিউটার অপারেটর ১',
    role: 'operator',
    mobile: '০১৭৭০০০০০১',
    nid: '১৯৯২০০০০০০০০০',
    joinedDate: '2025-03-01',
    photoUrl: '',
    nidDocUrl: '',
    status: 'active',
  },
  {
    id: 'stf_02',
    name: 'কম্পিউটার অপারেটর ২ (নারী উদ্যোক্তা)',
    role: 'operator',
    mobile: '০১৭৭০০০০০২',
    nid: '১৯৯৫০০০০০০০০০',
    joinedDate: '2025-03-01',
    photoUrl: '',
    nidDocUrl: '',
    status: 'active',
  },
];

export const inspectionChecklistData: InspectionChecklist[] = [
  { id: 1, itemText: 'এলএসএফসির দৃশ্যমান স্থানে অনুমতিপত্রের কপি টানানো রয়েছে কি না', complied: true, notes: 'সম্মুখের দেয়ালে ফ্রেমে টানানো আছে' },
  { id: 2, itemText: 'পরিশিষ্ট-৭ অনুযায়ী অনুমোদিত সেবামূলক ফি-এর তালিকা দৃষ্টিগোচর স্থানে টানানো আছে কি না', complied: true, notes: 'নাগরিক সেবা কাউন্টারে চার্ট টানানো' },
  { id: 3, itemText: 'সহায়তাকারীর নাম ও অনুমোদন সংক্রান্ত সাইনবোর্ড নির্ধারিত মাপে রয়েছে কি না', complied: true, notes: 'সেন্টারের প্রবেশদ্বারে স্থাপিত' },
  { id: 4, itemText: 'অনুমোদিত ভূমিসেবা ব্যতীত কোনো অবৈধ কাজ বা দালালি কার্যকলাপ হয় কি না', complied: true, notes: 'কঠোরভাবে নিষিদ্ধ ও নিয়ন্ত্রিত' },
  { id: 5, itemText: 'নাগরিকদের অভিযোগ দেওয়ার জন্য সিসিটিভি আওতাধীন তালাবদ্ধ অভিযোগ বাক্স রয়েছে কি না', complied: true, notes: 'বাক্সের চাবি এসিল্যান্ড মহোদয়ের নিকট সংরক্ষিত' },
  { id: 6, itemText: 'ডিজিটাল অভিযোগ রেজিস্টার ও সেবা রেজিস্টার নিয়মিত হালনাগাদ রয়েছে কি না', complied: true, notes: 'সফটওয়্যারে প্রতিদিন স্বয়ংক্রিয় সংরক্ষণ' },
  { id: 7, itemText: 'কম্পিউটার কর্মীদের জীবনবৃত্তান্ত, এনআইডি ও ছবি যথাযথভাবে সংরক্ষিত আছে কি না', complied: true, notes: 'ড্রাইভে ও ফাইলে সংরক্ষিত' },
  { id: 8, itemText: 'নাগরিকের ব্যক্তিগত খতিয়ান/দলিলের গোপনীয়তা বজায় রাখা হচ্ছে কি না', complied: true, notes: 'সিস্টেমে মাস্কিং ও সিকিউর এক্সেস পলিসি কার্যকর' },
  { id: 9, itemText: 'কম্পিউটার, প্রিন্টার, স্ক্যানার ও ন্যূনতম ১০ এমবিপিএস ব্রডব্যান্ড ইন্টারনেট সংযোগ সচল রয়েছে কি না', complied: true, notes: 'অপটিক্যাল ফাইবার সংযোগ সচল' },
  { id: 10, itemText: 'বিকল্প বিদ্যুৎ সরবরাহ ব্যবস্থা (আইপিএস/ইউপিএস/জেনারেটর) রয়েছে কি না', complied: true, notes: 'অনলাইন ইউপিএস ব্যাকআপ সক্রিয়' },
];

export const initialComplaints: ComplaintRecord[] = [
  {
    id: 'cmp_01',
    complaintDate: '2026-09-22',
    citizenName: 'মোঃ আলমগীর হোসেন',
    citizenMobile: '০১৭৩৩৪৫৬৭৮৯',
    subject: 'নামজারি আবেদন সার্ভার বিলম্ব',
    description: 'ভূমি মন্ত্রণালয়ের সার্ভারে মেইনটেনেন্স থাকায় আবেদনের ফি জমা দিতে ২০ মিনিট সময় বেশি লেগেছিল।',
    status: 'resolved',
    resolutionNotes: 'সার্ভার সচল হওয়ার সাথে সাথে সফলভাবে আবেদন দাখিল করে গ্রাহককে রিসিট প্রদান করা হয়েছে।',
  },
];
